[package]
name = "subnetfind"
version = "0.1.0"
authors = ["Matti Hänninen <matti@mjhanninen.fi>"]
edition = "2018"

[dependencies]
neli = "0.5.0-rc1"

[dependencies.clap]
version = "2.33.1"
default-features = false
features = ["wrap_help"]
